#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# This is displaying information about subdomains.
# Creating a function to query strings using awk

domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_info "$1" "www" 
  domain_info "$1" "Ib-01"
  domain_info "$1" "web-01"
  domain_info "$1" "web-02"

elif [ "$#" == 2 ]
then
  domain_info "$1" "$2"
fi
