#!/usr/bin/env bash
# install nginx when it listening on port 80

sudo apt-get -y update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx reload
