#!/usr/bin/env bash
# Install and configure HAproxy on my load balancer

sudo apt-get update
sudo apt-get install haproxy -y

# Configure loadbalancer
sudo vi /etc/haproxy/haproxy.cfg 
frontend odjels.tech_alx-frontend
        bind 0:80
	mode http
        default_backend odjels.tech_alx-backend

backend odjels.tech_alx-backend
        balance roundrobin
        server 118325-web-01 3.85.175.4 :80 check
        server 304250-web-02  100.26.175.217:80 check
EOT

# start the loadbalancer
sudo /etc/init.d/haproxy start

# set HAProxy to start at boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
