#!/usr/bin/env bash
# A script that loops through 1 to 10 using while

b=0
while ((b<10))
do
	if ((b == 3))
	then
		echo "bad luck"
	elif ((b == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((b+=1))
done
