#!/usr/bin/env bash
# This script prints texts and numbers depending on the condition set

b=1
while ((bi <= 20))
do
	echo $b
	case $b in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((b+=1))
done
